services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TZ: Europe/Madrid
    volumes:
      - vaultwarden_data:/data

volumes:
  vaultwarden_data:
    name: vaultwarden_data

# añadir estas líneas al final del archivo para proxy inverso 
networks:
  default:
    external: true
    name: proxy